import Head from 'next/head';

import { HomePage } from '@/src/components/home/Home-page';

import { EventsCategory, EventsData } from '@/interfaces/data.interface';
import { GetServerSideProps, InferGetServerSidePropsType } from 'next/types';

export default function Home({
	events_categories,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<HomePage events_categories={events_categories} />
		</>
	);
}

export const getServerSideProps: GetServerSideProps<
	Record<'events_categories', EventsCategory[]>
> = async () => {
	const json: EventsData = await import('../data/data.json');
	const { events_categories } = json;

	return {
		props: { events_categories },
	};
};
